### ISSUE TITLE
Not found .env

### ISSUE THREAD

**Issue by arminkit** [mhrefat/hrms#1]
Hello mhrefat
Un uploaded .ENV file? Where should I enter the database details?
Please send if you have a tutorial on installation
Thanks

**Comment by mhrefat** [comment]
Hello Dear,
I'm attaching the file here, if you could manually add the file in your
downloaded project, then I think it may work well.
Thank you,
M.h. Refat

**Comment by mhrefat** [comment]
Hello arminkit,
I have uploaded the .env file in the github, can you please check and close the issue?
